const coursesConfig = {
    "class-9-cbse": {
      name: "Class 9th CBSE",
      subjects: [
        {
          name: "Mathematics",
          chapters: [
            { name: "Number Systems", description: "Real numbers, rational and irrational numbers." },
            { name: "Polynomials", description: "Polynomial equations and factorization." },
            { name: "Coordinate Geometry", description: "Cartesian plane and plotting points." },
            { name: "Linear Equations in Two Variables", description: "Solving linear equations." },
            { name: "Introduction to Euclid's Geometry", description: "Axioms and postulates." },
            { name: "Lines and Angles", description: "Properties of lines and angles." },
            { name: "Triangles", description: "Properties and congruence of triangles." },
            { name: "Quadrilaterals", description: "Types and properties of quadrilaterals." },
            { name: "Areas of Parallelograms and Triangles", description: "Area calculations." },
            { name: "Circles", description: "Properties of circles and chords." },
            { name: "Constructions", description: "Geometric constructions using compass." },
            { name: "Heron's Formula", description: "Area of triangles using Heron's formula." },
            { name: "Surface Areas and Volumes", description: "Calculations for 3D shapes." },
            { name: "Statistics", description: "Data representation and measures." },
            { name: "Probability", description: "Basic probability concepts." },
          ],
        },
        {
          name: "Science",
          chapters: [
            { name: "Matter in Our Surroundings", description: "States of matter and properties." },
            { name: "Is Matter Around Us Pure", description: "Mixtures and separation techniques." },
            { name: "Atoms and Molecules", description: "Atomic structure and chemical formulas." },
            { name: "Structure of the Atom", description: "Subatomic particles and models." },
            { name: "The Fundamental Unit of Life", description: "Cell structure and functions." },
            { name: "Tissues", description: "Plant and animal tissues." },
            { name: "Diversity in Living Organisms", description: "Classification of organisms." },
            { name: "Motion", description: "Laws of motion and equations." },
            { name: "Force and Laws of Motion", description: "Newton's laws." },
            { name: "Gravitation", description: "Universal law of gravitation." },
            { name: "Work and Energy", description: "Work, energy, and power." },
            { name: "Sound", description: "Properties and propagation of sound." },
            { name: "Why Do We Fall Ill", description: "Health and diseases." },
            { name: "Natural Resources", description: "Conservation and resources." },
            { name: "Improvement in Food Resources", description: "Agricultural practices." },
          ],
        },
        {
          name: "Social Science",
          chapters: [
            { name: "India and the Contemporary World - I", description: "History: French Revolution, Socialism." },
            { name: "Contemporary India - I", description: "Geography: India’s physical features." },
            { name: "Democratic Politics - I", description: "Civics: Democracy and government." },
            { name: "Economics", description: "Basic economic concepts and poverty." },
          ],
        },
        {
          name: "English",
          chapters: [
            { name: "Beehive (Prose and Poetry)", description: "Selected prose and poems." },
            { name: "Moments (Supplementary Reader)", description: "Supplementary stories." },
          ],
        },
      ],
    },
    "class-10-cbse": {
      name: "Class 10th CBSE",
      subjects: [
        {
          name: "Mathematics",
          chapters: [
            { name: "Real Numbers", description: "Euclid’s division lemma and HCF." },
            { name: "Polynomials", description: "Zeros and factorization of polynomials." },
            { name: "Pair of Linear Equations in Two Variables", description: "Graphical and algebraic solutions." },
            { name: "Quadratic Equations", description: "Solving quadratic equations." },
            { name: "Arithmetic Progressions", description: "Sequences and series." },
            { name: "Triangles", description: "Similarity and congruence." },
            { name: "Coordinate Geometry", description: "Distance and section formulas." },
            { name: "Introduction to Trigonometry", description: "Trigonometric ratios." },
            { name: "Some Applications of Trigonometry", description: "Heights and distances." },
            { name: "Circles", description: "Tangents and properties." },
            { name: "Constructions", description: "Geometric constructions." },
            { name: "Areas Related to Circles", description: "Area and perimeter calculations." },
            { name: "Surface Areas and Volumes", description: "3D shapes calculations." },
            { name: "Statistics", description: "Mean, median, mode." },
            { name: "Probability", description: "Probability of events." },
          ],
        },
        {
          name: "Science",
          chapters: [
            { name: "Chemical Reactions and Equations", description: "Types of chemical reactions." },
            { name: "Acids, Bases and Salts", description: "Properties and reactions." },
            { name: "Metals and Non-metals", description: "Physical and chemical properties." },
            { name: "Carbon and its Compounds", description: "Organic chemistry basics." },
            { name: "Periodic Classification of Elements", description: "Periodic table." },
            { name: "Life Processes", description: "Nutrition, respiration, etc." },
            { name: "Control and Coordination", description: "Nervous and hormonal systems." },
            { name: "How do Organisms Reproduce", description: "Reproduction mechanisms." },
            { name: "Heredity and Evolution", description: "Genetics and evolution." },
            { name: "Light – Reflection and Refraction", description: "Optics principles." },
            { name: "Human Eye and Colourful World", description: "Vision and dispersion." },
            { name: "Electricity", description: "Electric circuits and Ohm’s law." },
            { name: "Magnetic Effects of Electric Current", description: "Magnetism and motors." },
            { name: "Sources of Energy", description: "Renewable and non-renewable energy." },
            { name: "Our Environment", description: "Ecosystems and conservation." },
            { name: "Management of Natural Resources", description: "Sustainable practices." },
          ],
        },
        {
          name: "Social Science",
          chapters: [
            { name: "India and the Contemporary World - II", description: "History: Nationalism in India." },
            { name: "Contemporary India - II", description: "Geography: Resources and development." },
            { name: "Democratic Politics - II", description: "Civics: Power sharing." },
            { name: "Understanding Economic Development", description: "Economics: Development and globalization." },
          ],
        },
        {
          name: "English",
          chapters: [
            { name: "First Flight (Prose and Poetry)", description: "Selected prose and poems." },
            { name: "Footprints Without Feet (Supplementary)", description: "Supplementary stories." },
          ],
        },
      ],
    },
    "class-11-pcm": {
      name: "Class 11th CBSE PCM",
      subjects: [
        {
          name: "Physics",
          chapters: [
            { name: "Physical World", description: "Scope of physics." },
            { name: "Units and Measurements", description: "Measurement systems." },
            { name: "Motion in a Straight Line", description: "Kinematics in one dimension." },
            { name: "Motion in a Plane", description: "Vectors and projectile motion." },
            { name: "Laws of Motion", description: "Newton’s laws and applications." },
            { name: "Work, Energy and Power", description: "Energy conservation." },
            { name: "System of Particles and Rotational Motion", description: "Center of mass and rotation." },
            { name: "Gravitation", description: "Universal gravitation." },
            { name: "Mechanical Properties of Solids", description: "Elasticity and stress." },
            { name: "Mechanical Properties of Fluids", description: "Fluid dynamics." },
            { name: "Thermal Properties of Matter", description: "Heat and thermodynamics." },
            { name: "Thermodynamics", description: "Laws of thermodynamics." },
            { name: "Kinetic Theory", description: "Kinetic theory of gases." },
            { name: "Oscillations", description: "Simple harmonic motion." },
            { name: "Waves", description: "Wave properties and sound." },
          ],
        },
        {
          name: "Chemistry",
          chapters: [
            { name: "Some Basic Concepts of Chemistry", description: "Mole concept and stoichiometry." },
            { name: "Structure of Atom", description: "Atomic models and quantum numbers." },
            { name: "Classification of Elements and Periodicity", description: "Periodic table trends." },
            { name: "Chemical Bonding and Molecular Structure", description: "Bond types and VSEPR." },
            { name: "States of Matter", description: "Gases and liquids." },
            { name: "Thermodynamics", description: "Enthalpy and entropy." },
            { name: "Equilibrium", description: "Chemical and ionic equilibrium." },
            { name: "Redox Reactions", description: "Oxidation and reduction." },
            { name: "Hydrogen", description: "Properties and compounds." },
            { name: "The s-Block Elements", description: "Alkali and alkaline earth metals." },
            { name: "The p-Block Elements", description: "Group 13-14 elements." },
            { name: "Organic Chemistry - Some Basic Principles", description: "Nomenclature and isomerism." },
            { name: "Hydrocarbons", description: "Alkanes, alkenes, alkynes." },
            { name: "Environmental Chemistry", description: "Pollution and green chemistry." },
          ],
        },
        {
          name: "Mathematics",
          chapters: [
            { name: "Sets", description: "Set theory and operations." },
            { name: "Relations and Functions", description: "Functions and their types." },
            { name: "Trigonometric Functions", description: "Trigonometric identities." },
            { name: "Principle of Mathematical Induction", description: "Proof by induction." },
            { name: "Complex Numbers and Quadratic Equations", description: "Complex numbers." },
            { name: "Linear Inequalities", description: "Solving inequalities." },
            { name: "Permutations and Combinations", description: "Counting principles." },
            { name: "Binomial Theorem", description: "Binomial expansions." },
            { name: "Sequences and Series", description: "Arithmetic and geometric progressions." },
            { name: "Straight Lines", description: "Lines in 2D geometry." },
            { name: "Conic Sections", description: "Circles, parabolas, ellipses." },
            { name: "Introduction to Three Dimensional Geometry", description: "3D coordinates." },
            { name: "Limits and Derivatives", description: "Calculus basics." },
            { name: "Mathematical Reasoning", description: "Logic and statements." },
            { name: "Statistics", description: "Measures of central tendency." },
            { name: "Probability", description: "Probability axioms." },
          ],
        },
        {
          name: "English",
          chapters: [
            { name: "Hornbill (Prose and Poetry)", description: "Selected prose and poems." },
            { name: "Snapshots (Supplementary Reader)", description: "Supplementary stories." },
          ],
        },
      ],
    },
    "class-11-pcb": {
      name: "Class 11th CBSE PCB",
      subjects: [
        {
          name: "Physics",
          chapters: [
            // Same as PCM Physics
            { name: "Physical World", description: "Scope of physics." },
            { name: "Units and Measurements", description: "Measurement systems." },
            { name: "Motion in a Straight Line", description: "Kinematics in one dimension." },
            { name: "Motion in a Plane", description: "Vectors and projectile motion." },
            { name: "Laws of Motion", description: "Newton’s laws and applications." },
            { name: "Work, Energy and Power", description: "Energy conservation." },
            { name: "System of Particles and Rotational Motion", description: "Center of mass and rotation." },
            { name: "Gravitation", description: "Universal gravitation." },
            { name: "Mechanical Properties of Solids", description: "Elasticity and stress." },
            { name: "Mechanical Properties of Fluids", description: "Fluid dynamics." },
            { name: "Thermal Properties of Matter", description: "Heat and thermodynamics." },
            { name: "Thermodynamics", description: "Laws of thermodynamics." },
            { name: "Kinetic Theory", description: "Kinetic theory of gases." },
            { name: "Oscillations", description: "Simple harmonic motion." },
            { name: "Waves", description: "Wave properties and sound." },
          ],
        },
        {
          name: "Chemistry",
          chapters: [
            // Same as PCM Chemistry
            { name: "Some Basic Concepts of Chemistry", description: "Mole concept and stoichiometry." },
            { name: "Structure of Atom", description: "Atomic models and quantum numbers." },
            { name: "Classification of Elements and Periodicity", description: "Periodic table trends." },
            { name: "Chemical Bonding and Molecular Structure", description: "Bond types and VSEPR." },
            { name: "States of Matter", description: "Gases and liquids." },
            { name: "Thermodynamics", description: "Enthalpy and entropy." },
            { name: "Equilibrium", description: "Chemical and ionic equilibrium." },
            { name: "Redox Reactions", description: "Oxidation and reduction." },
            { name: "Hydrogen", description: "Properties and compounds." },
            { name: "The s-Block Elements", description: "Alkali and alkaline earth metals." },
            { name: "The p-Block Elements", description: "Group 13-14 elements." },
            { name: "Organic Chemistry - Some Basic Principles", description: "Nomenclature and isomerism." },
            { name: "Hydrocarbons", description: "Alkanes, alkenes, alkynes." },
            { name: "Environmental Chemistry", description: "Pollution and green chemistry." },
          ],
        },
        {
          name: "Biology",
          chapters: [
            { name: "The Living World", description: "Characteristics of life." },
            { name: "Biological Classification", description: "Taxonomy and kingdoms." },
            { name: "Plant Kingdom", description: "Classification of plants." },
            { name: "Animal Kingdom", description: "Classification of animals." },
            { name: "Morphology of Flowering Plants", description: "Plant structures." },
            { name: "Anatomy of Flowering Plants", description: "Plant tissues." },
            { name: "Structural Organisation in Animals", description: "Animal tissues." },
            { name: "Cell: The Unit of Life", description: "Cell structure." },
            { name: "Biomolecules", description: "Proteins, carbohydrates, etc." },
            { name: "Cell Cycle and Cell Division", description: "Mitosis and meiosis." },
            { name: "Transport in Plants", description: "Water and nutrient transport." },
            { name: "Mineral Nutrition", description: "Plant nutrients." },
            { name: "Photosynthesis in Higher Plants", description: "Photosynthesis process." },
            { name: "Respiration in Plants", description: "Plant respiration." },
            { name: "Plant Growth and Development", description: "Plant hormones." },
            { name: "Digestion and Absorption", description: "Human digestive system." },
            { name: "Breathing and Exchange of Gases", description: "Respiratory system." },
            { name: "Body Fluids and Circulation", description: "Circulatory system." },
            { name: "Excretory Products and their Elimination", description: "Excretory system." },
            { name: "Locomotion and Movement", description: "Muscular and skeletal systems." },
            { name: "Neural Control and Coordination", description: "Nervous system." },
            { name: "Chemical Coordination and Integration", description: "Endocrine system." },
          ],
        },
        {
          name: "English",
          chapters: [
            { name: "Hornbill (Prose and Poetry)", description: "Selected prose and poems." },
            { name: "Snapshots (Supplementary Reader)", description: "Supplementary stories." },
          ],
        },
      ],
    },
    "class-12-pcm": {
      name: "Class 12th CBSE PCM",
      subjects: [
        {
          name: "Physics",
          chapters: [
            { name: "Electric Charges and Fields", description: "Electrostatics basics." },
            { name: "Electrostatic Potential and Capacitance", description: "Potential and capacitors." },
            { name: "Current Electricity", description: "Ohm’s law and circuits." },
            { name: "Moving Charges and Magnetism", description: "Magnetic fields." },
            { name: "Magnetism and Matter", description: "Magnetic properties." },
            { name: "Electromagnetic Induction", description: "Faraday’s laws." },
            { name: "Alternating Current", description: "AC circuits." },
            { name: "Electromagnetic Waves", description: "EM wave properties." },
            { name: "Ray Optics and Optical Instruments", description: "Reflection and refraction." },
            { name: "Wave Optics", description: "Interference and diffraction." },
            { name: "Dual Nature of Radiation and Matter", description: "Photoelectric effect." },
            { name: "Atoms", description: "Atomic models." },
            { name: "Nuclei", description: "Nuclear structure and reactions." },
            { name: "Semiconductor Electronics", description: "Diodes and transistors." },
            { name: "Communication Systems", description: "Basics of communication." },
          ],
        },
        {
          name: "Chemistry",
          chapters: [
            { name: "The Solid State", description: "Crystal structures." },
            { name: "Solutions", description: "Concentration and colligative properties." },
            { name: "Electrochemistry", description: "Redox reactions and cells." },
            { name: "Chemical Kinetics", description: "Reaction rates." },
            { name: "Surface Chemistry", description: "Adsorption and catalysis." },
            { name: "General Principles and Processes of Isolation of Elements", description: "Metallurgy." },
            { name: "The p-Block Elements", description: "Group 15-18 elements." },
            { name: "The d- and f-Block Elements", description: "Transition and inner transition elements." },
            { name: "Coordination Compounds", description: "Coordination chemistry." },
            { name: "Haloalkanes and Haloarenes", description: "Organic halides." },
            { name: "Alcohols, Phenols and Ethers", description: "Organic oxygen compounds." },
            { name: "Aldehydes, Ketones and Carboxylic Acids", description: "Carbonyl compounds." },
            { name: "Amines", description: "Organic nitrogen compounds." },
            { name: "Biomolecules", description: "Carbohydrates, proteins, etc." },
            { name: "Polymers", description: "Types and properties of polymers." },
            { name: "Chemistry in Everyday Life", description: "Drugs and chemicals." },
          ],
        },
        {
          name: "Mathematics",
          chapters: [
            { name: "Relations and Functions", description: "Types of functions." },
            { name: "Inverse Trigonometric Functions", description: "Properties and applications." },
            { name: "Matrices", description: "Matrix operations." },
            { name: "Determinants", description: "Properties and applications." },
            { name: "Continuity and Differentiability", description: "Calculus concepts." },
            { name: "Application of Derivatives", description: "Tangents and rates." },
            { name: "Integrals", description: "Integration techniques." },
            { name: "Application of Integrals", description: "Area under curves." },
            { name: "Differential Equations", description: "Solving differential equations." },
            { name: "Vector Algebra", description: "Vectors and their operations." },
            { name: "Three Dimensional Geometry", description: "Lines and planes in 3D." },
            { name: "Linear Programming", description: "Optimization problems." },
            { name: "Probability", description: "Conditional probability and Bayes’ theorem." },
          ],
        },
        {
          name: "English",
          chapters: [
            { name: "Flamingo (Prose and Poetry)", description: "Selected prose and poems." },
            { name: "Vistas (Supplementary Reader)", description: "Supplementary stories." },
          ],
        },
      ],
    },
    "class-12-pcb": {
      name: "Class 12th CBSE PCB",
      subjects: [
        {
          name: "Physics",
          chapters: [
            // Same as PCM Physics
            { name: "Electric Charges and Fields", description: "Electrostatics basics." },
            { name: "Electrostatic Potential and Capacitance", description: "Potential and capacitors." },
            { name: "Current Electricity", description: "Ohm’s law and circuits." },
            { name: "Moving Charges and Magnetism", description: "Magnetic fields." },
            { name: "Magnetism and Matter", description: "Magnetic properties." },
            { name: "Electromagnetic Induction", description: "Faraday’s laws." },
            { name: "Alternating Current", description: "AC circuits." },
            { name: "Electromagnetic Waves", description: "EM wave properties." },
            { name: "Ray Optics and Optical Instruments", description: "Reflection and refraction." },
            { name: "Wave Optics", description: "Interference and diffraction." },
            { name: "Dual Nature of Radiation and Matter", description: "Photoelectric effect." },
            { name: "Atoms", description: "Atomic models." },
            { name: "Nuclei", description: "Nuclear structure and reactions." },
            { name: "Semiconductor Electronics", description: "Diodes and transistors." },
            { name: "Communication Systems", description: "Basics of communication." },
          ],
        },
        {
          name: "Chemistry",
          chapters: [
            // Same as PCM Chemistry
            { name: "The Solid State", description: "Crystal structures." },
            { name: "Solutions", description: "Concentration and colligative properties." },
            { name: "Electrochemistry", description: "Redox reactions and cells." },
            { name: "Chemical Kinetics", description: "Reaction rates." },
            { name: "Surface Chemistry", description: "Adsorption and catalysis." },
            { name: "General Principles and Processes of Isolation of Elements", description: "Metallurgy." },
            { name: "The p-Block Elements", description: "Group 15-18 elements." },
            { name: "The d- and f-Block Elements", description: "Transition and inner transition elements." },
            { name: "Coordination Compounds", description: "Coordination chemistry." },
            { name: "Haloalkanes and Haloarenes", description: "Organic halides." },
            { name: "Alcohols, Phenols and Ethers", description: "Organic oxygen compounds." },
            { name: "Aldehydes, Ketones and Carboxylic Acids", description: "Carbonyl compounds." },
            { name: "Amines", description: "Organic nitrogen compounds." },
            { name: "Biomolecules", description: "Carbohydrates, proteins, etc." },
            { name: "Polymers", description: "Types and properties of polymers." },
            { name: "Chemistry in Everyday Life", description: "Drugs and chemicals." },
          ],
        },
        {
          name: "Biology",
          chapters: [
            { name: "Reproduction in Organisms", description: "Modes of reproduction." },
            { name: "Sexual Reproduction in Flowering Plants", description: "Plant reproduction." },
            { name: "Human Reproduction", description: "Human reproductive system." },
            { name: "Reproductive Health", description: "Health and contraception." },
            { name: "Principles of Inheritance and Variation", description: "Genetics." },
            { name: "Molecular Basis of Inheritance", description: "DNA and genes." },
            { name: "Evolution", description: "Theories of evolution." },
            { name: "Human Health and Disease", description: "Diseases and immunity." },
            { name: "Strategies for Enhancement in Food Production", description: "Agriculture." },
            { name: "Microbes in Human Welfare", description: "Uses of microbes." },
            { name: "Biotechnology: Principles and Processes", description: "Biotech basics." },
            { name: "Biotechnology and its Applications", description: "Applications of biotech." },
            { name: "Organisms and Populations", description: "Ecology and populations." },
            { name: "Ecosystem", description: "Ecosystem structure and function." },
            { name: "Biodiversity and Conservation", description: "Biodiversity conservation." },
            { name: "Environmental Issues", description: "Pollution and global issues." },
          ],
        },
        {
          name: "English",
          chapters: [
            { name: "Flamingo (Prose and Poetry)", description: "Selected prose and poems." },
            { name: "Vistas (Supplementary Reader)", description: "Supplementary stories." },
          ],
        },
      ],
    },
  };
  
  module.exports = coursesConfig;